version: '{build}'
image: Visual Studio 2015
platform:
- x86
- x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    PYTHONWARNINGS: ignore:DEPRECATION
    MSSdk: 1
  matrix:
  - PYTHON: 36
  - PYTHON: 37
  - PYTHON: 38
install:
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
- ps: |
    if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
    $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
    python -m pip install --disable-pip-version-check --upgrade --no-warn-script-location pip build virtualenv
build_script:
- ps: python -m pip install .
test_script:
- ps: python setup.py test
